### ISSUE TITLE
eTLD + 1 similarity

### ISSUE THREAD

**Issue by monicachew** [monicachew/g-analysis#9]
Map foo.example.com and bar.example.com to example.com and compute overlap

**Comment by monicachew** [comment]
Fixed by https://github.com/monicachew/g-analysis/pull/10

**Comment by kontaxis** [comment]
./eTLD+1.py ../dummy-sb-server/tmp_out/domains.txt | egrep -v "^#" > ../dummy-sb-server/tmp_out/domains.txt-eTLD+1
./eTLD+1.py ../dummy-sb-server/tmp_out_g/domains.txt | egrep -v "^#" > ../dummy-sb-server/tmp_out_g/domains.txt-eTLD+1

./jaccard_index.sh ../dummy-sb-server/tmp_out/domains.txt-eTLD+1 ../dummy-sb-server/tmp_out_g/domains.txt-eTLD+1

distinct elements incommon: 762
distinct elements combined: 2940
jaccard index: .25918367346938775510

Compared to #6 we have more elements in common since we are now grouping the subdomains.
We get fewer distinct elements in their union for the same reason.
Overall the index is higher which means more overlap but it's only 25%.

**Comment by fmarier** [comment]
So if I understand this correctly, if we were to move TP to the intersection of D and G, we'd only block  25% of the sub-resources that we're currently blocking (given we're using D exclusively)?

**Comment by kontaxis** [comment]
The index is intersection / union so we can't talk about either list by itself. The 25% tells us they are dissimilar (100% would make them identical).

To answer that question we would compare their intersection of 762 distinct domains to the 1610 distinct domains from list D alone (eTLD+1 grouping). We see that the intersection is only 47% list D.

**Comment by fmarier** [comment]
Ah right, that makes sense. ~50% is still not great, but it's not as bad :)

**Comment by monicachew** [comment]
What? No, 50% is terrible :) We should not pay and do extra work to reduce coverage. Also the regexp conversion is unsafe compared to a straight domain list.

**Comment by monicachew** [comment]
What are the sizes pre-eTLD grouping? Post eTLD grouping it looks like
- Disconnect alone: 842 (29%)
- Ghostery alone:  1336 (45%)
- Intersection: 762 (26%)

**Comment by kontaxis** [comment]
pre-eTLD grouping

Disconnect
$ sort ../dummy-sb-server/tmp_out/domains.txt | uniq | wc -l
1631

Ghostery
$ sort ../dummy-sb-server/tmp_out_g/domains.txt | uniq | wc -l
2154

post-eTLD grouping

Disconnect
$ sort ../dummy-sb-server/tmp_out/domains.txt-eTLD+1 | uniq | wc -l
1610

Ghostery
$ sort ../dummy-sb-server/tmp_out_g/domains.txt-eTLD+1 | uniq | wc -l
2092

**Comment by monicachew** [comment]
What's the intersection of pre-eTLD? (1631 and 2154)?

**Comment by kontaxis** [comment]
That's #6, i.e., 596 common elements.

**Comment by kontaxis** [comment]
pre-eTLD grouping
- Disconnect alone: 1631 unique - 596 in intersection = 1035
- Ghostery alone:  3189 total unique - 596 in common - 1035 in D alone = 1558
- Intersection: 596
